name: network_requests
description: An easy-to-use http network requests handler.
version: 2.0.3
homepage: https://github.com/Coder-Manuel/network_requests

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  http: ^1.1.0
  mime: ^1.0.4
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
