name: http_interceptor
description:
  A lightweight, simple plugin that allows you to intercept request and response
  objects and modify them if desired.
version: 2.0.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
